namespace Perf.Holders.Generator.Builders;

using Internal;
using Types;

sealed class OptionSystemTextJsonSourceBuilder(OptionHolderContextInfo contextInfo) {
    const string Exceptions = "global::Perf.Holders.Exceptions.OptionHolderExceptions";
    readonly InterpolatedStringBuilder sb = new(stringBuilder: new(8000));

    readonly CompInfo compInfo = contextInfo.CompInfo;
    int bracesToCloseOnEnd;
    OptionHolderContextInfo context = contextInfo;

    void Preparation() {
        if (compInfo.SupportNullableAnnotation() is false && context.Some.IsStruct is false) {
            context = context with {
                Some = context.Some with {
                    TypeNullable = context.Some.Type
                }
            };
        }
    }

    public string WriteAllAndBuild() {
        Preparation();
        DeclareTopLevelStatements();
        WriteJsonConverter();
        // WriteEndOfType();
        WriteEndOfFile();
        return sb.ToString();
    }

    void DeclareTopLevelStatements() {
        sb.AppendLine("// <auto-generated />");
        if (compInfo.SupportNullableAnnotation()) {
            sb.AppendLine("#nullable enable");
        }

        if (compInfo.SupportFileScopedNamespace()) {
            sb.AppendLine("namespace Perf.Holders.Serialization.SystemTextJson;");
        } else {
            sb.AppendLine("namespace Perf.Holders.Serialization.SystemTextJson\n{");
            bracesToCloseOnEnd++;
        }
    }

    void WriteJsonConverter() {
        var accessibility = context.Option.Accessibility is TypeAccessibility.Public ? "public " : "";
        const string stj = "global::System.Text.Json";
        const string stjSer = "global::System.Text.Json.Serialization";
        sb.AppendInterpolatedLine(
            $$"""
            {{accessibility}}sealed class JsonConverter_{{context.Option.OnlyName}} : {{stjSer}}.JsonConverter<{{context.Option.GlobalName}}> {
                public static readonly JsonConverter_{{context.Option.OnlyName}} Instance = new();
                
                public override void Write({{stj}}.Utf8JsonWriter writer, {{context.Option.GlobalName}} value, {{stj}}.JsonSerializerOptions options) {
                    if(value.{{context.IsSome.Property}}) {
                        {{stj}}.JsonSerializer.Serialize(writer, value.{{context.Some.Property}}, options);
                    } else {
                        writer.WriteNullValue();
                    }
                }
                
                public override {{context.Option.GlobalName}} Read(ref {{stj}}.Utf8JsonReader reader, Type typeToConvert, {{stj}}.JsonSerializerOptions options) {
                    if (reader.TokenType == {{stj}}.JsonTokenType.Null) {
                        reader.Read();
                        return default;
                    }
                    
                    var value = {{stj}}.JsonSerializer.Deserialize<{{context.Some.Type}}>(ref reader, options)!;
                    return value;
                }
            }
            """
        );
    }

    void WriteEndOfFile() {
        for (var i = 0; i < bracesToCloseOnEnd; i++) {
            sb.Append('}');
        }

        sb.AppendLine();
    }
}
