namespace Perf.Holders.Generator.Builders;

using Internal;
using Types;

sealed class OptionMessagePackSourceBuilder(OptionHolderContextInfo contextInfo) {
    readonly InterpolatedStringBuilder sb = new(stringBuilder: new());

    OptionHolderContextInfo context = contextInfo;
    readonly CompInfo compInfo = contextInfo.CompInfo;
    int bracesToCloseOnEnd;

    void Preparation() {
        if (compInfo.SupportNullableAnnotation() is false && context.Some.IsStruct is false) {
            context = context with {
                Some = context.Some with {
                    TypeNullable = context.Some.Type
                }
            };
        }
    }

    public string WriteAllAndBuild() {
        Preparation();
        DeclareTopLevelStatements();
        WriteMessagePackFormatter();
        WriteEndOfFile();
        return sb.ToString();
    }

    void DeclareTopLevelStatements() {
        sb.AppendLine("// <auto-generated />");
        if (compInfo.SupportNullableAnnotation()) {
            sb.AppendLine("#nullable enable");
        }

        if (compInfo.SupportFileScopedNamespace()) {
            sb.AppendLine("namespace Perf.Holders.Serialization.MessagePack;");
        } else {
            sb.AppendLine("namespace Perf.Holders.Serialization.MessagePack\n{");
            bracesToCloseOnEnd++;
        }
    }

    void WriteMessagePackFormatter() {
        var accessibility = context.GlobalAccessibility is TypeAccessibility.Public ? "public " : "";
        const string msgPack = "global::MessagePack";
        var typeParameterConstraint = context.Some.IsTypeParameter ? $"    where {context.Some.Type} : notnull " : "";
        sb.AppendInterpolatedLine(
            $$"""
            {{accessibility}}sealed class MessagePackFormatter_{{context.Option.DeclarationName}} : {{msgPack}}.Formatters.IMessagePackFormatter<{{context.Option.GlobalName}}>
            {{typeParameterConstraint}}{
                public static readonly MessagePackFormatter_{{context.Option.DeclarationName}} Instance = new();
                
                public void Serialize(ref {{msgPack}}.MessagePackWriter writer, {{context.Option.GlobalName}} value, {{msgPack}}.MessagePackSerializerOptions options) {
                    if(value.{{context.IsSome.Property}}) {
                        {{msgPack}}.MessagePackSerializer.Serialize(ref writer, value.{{context.Some.Property}}, options);
                    } else {
                        writer.WriteNil();
                    }
                }
                
                public {{context.Option.GlobalName}} Deserialize(ref {{msgPack}}.MessagePackReader reader, {{msgPack}}.MessagePackSerializerOptions options) {
                    if (reader.TryReadNil()) {
                        return default;
                    }
                    var value = {{msgPack}}.MessagePackSerializer.Deserialize<{{context.Some.Type}}>(ref reader, options);
                    return value;
                }
            }
            """
        );
    }

    void WriteEndOfFile() {
        for (var i = 0; i < bracesToCloseOnEnd; i++) {
            sb.Indent--;
            sb.Append('}');
        }

        sb.AppendLine();
    }
}
